### ISSUE TITLE
Comments are barely visible

### ISSUE THREAD

**Issue by imolorhe** [pantajoe/altair-nord-theme#1]
Hey @pantajoe, thanks for this Altair theme! This is the first altair theme I see open sourced ❤️ 

Considering my issue, it's probably a minor thing (depending on if it was intentional or not) but the comments are practically invisible for me. I can highlight the text though and see it well, so might be the intention.

For the most part wanted to use this issue to appreciate you for your effort! 😄 💪🏾

**Comment by pantajoe** [comment]
Hello there! I'm happy, you like this Nord Theme port to your application 😄  
I have to say, I'm pretty happy I found your GQL IDE. It is by far the most bug-free and intuitive GQL IDE that allows me to save my queries properly in collections. 😄 

I appreciate the hint! However, I use the Nord theme in most of my applications, and the comments always look as dark as in this port. 😅  Maybe I could add a bullet point in the README suggesting another color from the Nord Theme color palette.

**Comment by imolorhe** [comment]
Fair enough. I just wasn't sure if it was intended or not. But good to know!
