### ISSUE TITLE
Make into an Altair plugin

### ISSUE THREAD

**Issue by imolorhe** [pantajoe/altair-nord-theme#2]
Hello again!

I just released v3.1.0 of Altair which includes functionality to [write a theme plugin](https://altair.sirmuel.design/docs/plugins/writing-plugin.html) using `ctx.theme.add(themeName, themeConfig)`. Considering you already created a repo for this theme, perhaps you would also consider creating a plugin from it as well 🙂 

Here's how it would look within a plugin: https://github.com/XKojiMedia/altair-graphql-plugin-graphql-explorer/blob/master/src/index.js#L26-L31

**Comment by pantajoe** [comment]
Hi! That's cool. Right now, I have a lot on my plate, but I'm confident I'll write one soon. Thanks for the update! 😄

**Comment by pantajoe** [comment]
@imolorhe Hey, it's been a while! I've managed to port this theme config to a plugin. Just a question though: Does this repository adhere to your plugin standards? (It's also published already: https://www.npmjs.com/package/altair-graphql-plugin-nord-theme) Also, how would I install it?

**Comment by imolorhe** [comment]
Nice! There's one small issue. The manifest_version is set to "1" which indicates you are using the older version of the plugin implementation. You need to change that to "2" and then it would be visible in the plugin list in Altair. Alternatively, you can add it to Altair manually by specifying the plugin name (altair-graphql-plugin-nord-theme) under the settings.

Also you are missing the `plugin_class` in the manifest.json. The docs mentioned that this is optional which is wrong 😅 it is required for Altair to know how to identify the plugin. Currently Altair doesn't throw an error when this happens making it difficult to know but I'm changing that now.

And finally, you can indicate if you want the theme to be enabled in dark mode as well using `ctx.theme.enable(themeName, true)` where the second argument is `true` for dark mode. (I'll also add that to the docs)

Hope that helps 😊

**Comment by pantajoe** [comment]
Thanks for your quick response and help!
I hope, I implemented all your remarks correctly 😅 
However, the "Available Plugins" modal still does not show this plugin 😢 :
![image](https://user-images.githubusercontent.com/31014018/131473552-6c84e7f1-e94f-48f3-813b-8f23e3531f61.png)

I also tried adding the full name `altair-graphql-plugin-nord-theme` under "Enabled Plugins" in the settings pane, but I still could not select the theme `nord` in the setting spane.

What am I missing?

**Comment by pantajoe** [comment]
It appears to be loaded when I enter the full name of the plugin (`altair-graphql-plugin-nord-theme`):
![image](https://user-images.githubusercontent.com/31014018/131501963-c350f3a1-61ee-4fb0-a3b6-96803ee5930a.png)

However, as you can see in the image, I cannot select the nord theme and the nord theme is not eligible at all:
![image](https://user-images.githubusercontent.com/31014018/131502127-0434b199-b2fc-4098-930f-fabbc1880d2a.png)

**Comment by imolorhe** [comment]
@pantajoe You've set it up correctly 🙂 The issue at the moment is that jsdelivr busts their cache after 24 hours, so it's still using the old version. You can forcefully retrieve the correct version by specifying the version when you add the plugin string .i.e. `altair-graphql-plugin-nord-theme@0.0.3`. So by tomorrow, it should all be working fine.

**Comment by pantajoe** [comment]
Great, you were right! 😊 
![image](https://user-images.githubusercontent.com/31014018/131553976-078c186e-1ffe-4500-8b32-945b6c089938.png)
Thanks, keep it up!
